odf:
  cloudProvider:
    storageClass: ocs-storagecluster-cephfs
  
  ocs:
    namespace: openshift-storage
    mon:
      requests:
         cpu: 1
         memory: 2Gi
    mds:
      requests:
        cpu: 3
        memory: 8Gi
    mgr:
      requests:
        cpu: 1
        memory: 3Gi
    noobaacore:
      requests:
        cpu: 1
        memory: 4Gi
    noobaadb:
      requests:
        cpu: 1
        memory: 4Gi
    osd:
      requests:
        cpu: 2
        memory: 5Gi
      pvc:
        storage: 2Ti
  
  toolbox:
    name: ocsinit
    enableCephTools: true
  
  #Define the odf storageSystem parameters
  storageSystem:
    deploy: false
    name: ocs-storagecluster-storagesystem
    namespace: openshift-storage
    spec:
      kind: storagecluster.ocs.openshift.io/v1
      name: ocs-storagecluster
      namespace: ""
