kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol-db-noobaa-db-pg-0
  annotations:
    pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
spec:
  capacity:
    storage: 100Gi
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-db-noobaa-db-pg-0
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1710450330134-8081-ebs.csi.aws.com
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp3-csi
  volumeMode: Filesystem
