apiVersion: ocs.openshift.io/v1
kind: OCSInitialization
metadata:
  name: {{ .Values.odf.toolbox.name }}
  namespace: openshift-storage
  annotations:    
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  enableCephTools: {{ .Values.odf.toolbox.enableCephTools }}
