{{- if eq .Values.odf.storageSystem.deploy true }}
---
apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  name: {{ .Values.odf.storageSystem.name }}
  namespace: openshift-storage
spec:
  kind: storagecluster.ocs.openshift.io/v1
  name: {{ .Values.odf.storageSystem.name }}
  namespace: openshift-storage
{{- end }}
